spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderFallback
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentFallback
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**
          filters:
            - name: CircuitBreaker
              args:
                name: client-service
                fallbackuri: forward:/clientFallback
        - id: produit-service
          uri: lb://PRODUIT-SERVICE
          predicates:
            - Path=/produit/**
          filters:
            - name: CircuitBreaker
              args:
                name: produit-service
                fallbackuri: forward:/produitFallback
            

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


